# Generated by Django 5.0.7 on 2024-08-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_responses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responses',
            new_name='Response',
        ),
    ]
